SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS ATTACHMENT;
DROP TABLE IF EXISTS CHECKLIST_ITEM;
DROP TABLE IF EXISTS CHECKLIST;
DROP TABLE IF EXISTS CARD_LABEL_ASSIGNMENT;
DROP TABLE IF EXISTS LABEL;
DROP TABLE IF EXISTS CARD_DEPENDENCY;
DROP TABLE IF EXISTS CARD_ASSIGNMENT;
DROP TABLE IF EXISTS CARD;
DROP TABLE IF EXISTS LIST;
DROP TABLE IF EXISTS BOARD_MEMBER;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS WORKSPACE;
DROP TABLE IF EXISTS PRO_USER;
DROP TABLE IF EXISTS FREE_USER;
DROP TABLE IF EXISTS USER_PROFILE;
DROP TABLE IF EXISTS USER_PREFERENCE;
DROP TABLE IF EXISTS USER_POWER_UP;
DROP TABLE IF EXISTS USER_ACCOUNT;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE USER_ACCOUNT (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password_hash VARCHAR(255) NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    CONSTRAINT chk_email_format CHECK (Email LIKE '%@%'),
    CONSTRAINT chk_password_length CHECK (CHAR_LENGTH(Password_hash) >= 6)
);

CREATE TABLE USER_POWER_UP (
    User_ID INT NOT NULL,
    Power_Up_Name VARCHAR(100) NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (User_ID, Power_Up_Name),
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);

CREATE TABLE USER_PREFERENCE (
    User_ID INT PRIMARY KEY,
    Theme_Mode VARCHAR(50),
    Language VARCHAR(50),
    Notification_Setting VARCHAR(50),
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);

CREATE TABLE USER_PROFILE (
    Profile_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT UNIQUE NOT NULL,
    First_Name VARCHAR(100),
    Last_Name VARCHAR(100),
    Time_zone VARCHAR(100),
    Contact VARCHAR(255),
    Avatar_Url TEXT,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);

CREATE TABLE FREE_USER (
    User_ID INT PRIMARY KEY,
    Ad_Tracking_ID VARCHAR(255),
    Storage_Limit INT,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    CONSTRAINT chk_storage_limit CHECK (Storage_Limit >= 0),
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);

CREATE TABLE PRO_USER (
    User_ID INT PRIMARY KEY,
    Payment_Method VARCHAR(100),
    Next_Billing_Date DATETIME,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);

CREATE TABLE WORKSPACE (
    Workspace_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Owner_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (Owner_ID) REFERENCES USER_ACCOUNT(User_ID)
);

CREATE TABLE BOARD (
    Board_ID INT AUTO_INCREMENT PRIMARY KEY,
    Board_Title VARCHAR(255) NOT NULL,
    Visibility_Status VARCHAR(50),
    Workspace_ID INT NOT NULL,
    Total_Members INT DEFAULT 0,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    CONSTRAINT chk_total_members CHECK (Total_Members >= 0),
    FOREIGN KEY (Workspace_ID) REFERENCES WORKSPACE(Workspace_ID) ON DELETE CASCADE
);

CREATE TABLE BOARD_MEMBER (
    User_ID INT NOT NULL,
    Board_ID INT NOT NULL,
    Role VARCHAR(100),
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (User_ID, Board_ID),
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Board_ID) REFERENCES BOARD(Board_ID) ON DELETE CASCADE
);

CREATE TABLE LIST (
    List_ID INT AUTO_INCREMENT PRIMARY KEY,
    List_Name VARCHAR(255) NOT NULL,
    Position INT NOT NULL,
    Board_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    CONSTRAINT chk_list_position CHECK (Position >= 0),
    FOREIGN KEY (Board_ID) REFERENCES BOARD(Board_ID) ON DELETE CASCADE
);

CREATE TABLE CARD (
    Card_ID INT AUTO_INCREMENT PRIMARY KEY,
    Card_Title VARCHAR(255) NOT NULL,
    Description TEXT,
    Start_Date DATETIME,
    Due_Date DATETIME,
    Is_Due_Complete BOOLEAN DEFAULT FALSE,
    Duration INT,
    List_ID INT NOT NULL,
    Cover_Attachment_ID INT, 
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    CONSTRAINT chk_dates CHECK (Due_Date >= Start_Date OR Due_Date IS NULL OR Start_Date IS NULL),
    FOREIGN KEY (List_ID) REFERENCES LIST(List_ID) ON DELETE CASCADE
);

CREATE TABLE CARD_ASSIGNMENT (
    User_ID INT NOT NULL,
    Card_ID INT NOT NULL,
    Assignment_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (User_ID, Card_ID),
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE
);

CREATE TABLE CARD_DEPENDENCY (
    Blocked_Card_ID INT NOT NULL,
    Blocker_Card_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (Blocked_Card_ID, Blocker_Card_ID),
    CONSTRAINT chk_not_self_blocking CHECK (Blocked_Card_ID <> Blocker_Card_ID),
    FOREIGN KEY (Blocked_Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE,
    FOREIGN KEY (Blocker_Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE
);

CREATE TABLE LABEL (
    Label_ID INT AUTO_INCREMENT PRIMARY KEY,
    Label_Name VARCHAR(255) NOT NULL,
    Color_Code VARCHAR(20),
    Board_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (Board_ID) REFERENCES BOARD(Board_ID) ON DELETE CASCADE
);

CREATE TABLE CARD_LABEL_ASSIGNMENT (
    Card_ID INT NOT NULL,
    Label_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (Card_ID, Label_ID),
    FOREIGN KEY (Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE,
    FOREIGN KEY (Label_ID) REFERENCES LABEL(Label_ID) ON DELETE CASCADE
);
CREATE TABLE CHECKLIST (
    Card_ID INT NOT NULL,
    Checklist_ID INT NOT NULL,
    Checklist_Title VARCHAR(255) NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (Card_ID, Checklist_ID),
    FOREIGN KEY (Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE
);
CREATE TABLE CHECKLIST_ITEM (
    Card_ID INT NOT NULL,
    Checklist_ID INT NOT NULL,
    Item_ID INT NOT NULL,
    Content TEXT NOT NULL,
    Is_Completed BOOLEAN DEFAULT FALSE,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    PRIMARY KEY (Card_ID, Checklist_ID, Item_ID),
    FOREIGN KEY (Card_ID, Checklist_ID) REFERENCES CHECKLIST(Card_ID, Checklist_ID) ON DELETE CASCADE
);
CREATE TABLE ATTACHMENT (
    Card_ID INT NOT NULL,
    Attachment_ID INT AUTO_INCREMENT PRIMARY KEY,
    File_Name VARCHAR(255) NOT NULL,
    File_Url TEXT NOT NULL,
    File_Type VARCHAR(100),
    Upload_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    User_ID INT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    FOREIGN KEY (Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);
CREATE TABLE COMMENT (
    Card_ID INT NOT NULL,
    Comment_ID INT NOT NULL,
    Content TEXT NOT NULL,
    Created_At DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_At DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Is_Deleted BOOLEAN DEFAULT FALSE,
    Deleted_At DATETIME NULL,
    Is_Edited BOOLEAN DEFAULT FALSE,
    User_ID INT NOT NULL,
    PRIMARY KEY (Card_ID, Comment_ID),
    FOREIGN KEY (Card_ID) REFERENCES CARD(Card_ID) ON DELETE CASCADE,
    FOREIGN KEY (User_ID) REFERENCES USER_ACCOUNT(User_ID) ON DELETE CASCADE
);
ALTER TABLE CARD
ADD CONSTRAINT fk_card_cover_attachment
FOREIGN KEY (Cover_Attachment_ID) 
REFERENCES ATTACHMENT(Attachment_ID)
ON DELETE SET NULL;